import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <div className="flex flex-row w-screen h-screen">
                    <div className="flex flex-col w-1/4 h-full overflow-hidden">
                        <div className="bg-blue-500 h-20 w-full flex items-center pl-2">
                            <h1 className="text-white text-xl">Library App</h1>
                        </div>
                        <div className="bg-white h-full w-full flex flex-col pt-10">
                            <Link href={"/book"}>
                                <div className="h-10 w-full px-5 border-b border-black flex items-center hover:backdrop-brightness-90">
                                    <p className="text-black text-base">Book</p>
                                </div>
                            </Link>
                            <Link href={"/category"}>
                                <div className="h-10 w-full px-5 border-b border-black flex items-center hover:backdrop-brightness-90">
                                    <p className="text-black text-base">
                                        Category
                                    </p>
                                </div>
                            </Link>
                        </div>
                    </div>
                    <div className="flex flex-col w-full">
                        <header className="w-full h-20 bg-white flex justify-end items-center pr-20">
                            <p className="text-black text-lg font-bold">
                                username
                            </p>
                        </header>
                        <div className="p-5 bg-slate-200 w-full h-full overflow-auto">
                            {children}
                        </div>
                    </div>
                </div>
            </body>
        </html>
    );
}
