import LayoutComponent from "../components/layoutComponent";
import "../globals.css";

export const metadata = {
    title: "Library App",
    description: "Generated by Naufal",
};

export default function DashboardLayout({ children }) {
    return <LayoutComponent>{children}</LayoutComponent>;
}
